<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [

            [
                'name'=>'Indonesia',
                'code'=>'ID',
                'iso2'=>'ID',
                'iso3'=>'IDN',
                'currency'=>'IDR',
                'region'=>'Asia',
                'language'=>'Indonesian',
                'capital'=>'Jakarta',
                'latitude'=>-6.2088,
                'longitude'=>106.8456,
                'flag'=>'https://flagcdn.com/w320/id.png',
            ],

            [
                'name'=>'Singapore',
                'code'=>'SG',
                'iso2'=>'SG',
                'iso3'=>'SGP',
                'currency'=>'SGD',
                'region'=>'Asia',
                'language'=>'English',
                'capital'=>'Singapore',
                'latitude'=>1.3521,
                'longitude'=>103.8198,
                'flag'=>'https://flagcdn.com/w320/sg.png',
            ],

            [
                'name'=>'China',
                'code'=>'CN',
                'iso2'=>'CN',
                'iso3'=>'CHN',
                'currency'=>'CNY',
                'region'=>'Asia',
                'language'=>'Chinese',
                'capital'=>'Beijing',
                'latitude'=>39.9042,
                'longitude'=>116.4074,
                'flag'=>'https://flagcdn.com/w320/cn.png',
            ],

            [
                'name'=>'Japan',
                'code'=>'JP',
                'iso2'=>'JP',
                'iso3'=>'JPN',
                'currency'=>'JPY',
                'region'=>'Asia',
                'language'=>'Japanese',
                'capital'=>'Tokyo',
                'latitude'=>35.6762,
                'longitude'=>139.6503,
                'flag'=>'https://flagcdn.com/w320/jp.png',
            ],

            [
                'name'=>'South Korea',
                'code'=>'KR',
                'iso2'=>'KR',
                'iso3'=>'KOR',
                'currency'=>'KRW',
                'region'=>'Asia',
                'language'=>'Korean',
                'capital'=>'Seoul',
                'latitude'=>37.5665,
                'longitude'=>126.9780,
                'flag'=>'https://flagcdn.com/w320/kr.png',
            ],

            [
                'name'=>'United States',
                'code'=>'US',
                'iso2'=>'US',
                'iso3'=>'USA',
                'currency'=>'USD',
                'region'=>'North America',
                'language'=>'English',
                'capital'=>'Washington D.C.',
                'latitude'=>38.9072,
                'longitude'=>-77.0369,
                'flag'=>'https://flagcdn.com/w320/us.png',
            ],

            [
                'name'=>'Germany',
                'code'=>'DE',
                'iso2'=>'DE',
                'iso3'=>'DEU',
                'currency'=>'EUR',
                'region'=>'Europe',
                'language'=>'German',
                'capital'=>'Berlin',
                'latitude'=>52.5200,
                'longitude'=>13.4050,
                'flag'=>'https://flagcdn.com/w320/de.png',
            ],

            [
                'name'=>'Netherlands',
                'code'=>'NL',
                'iso2'=>'NL',
                'iso3'=>'NLD',
                'currency'=>'EUR',
                'region'=>'Europe',
                'language'=>'Dutch',
                'capital'=>'Amsterdam',
                'latitude'=>52.3676,
                'longitude'=>4.9041,
                'flag'=>'https://flagcdn.com/w320/nl.png',
            ],

            [
                'name'=>'United Arab Emirates',
                'code'=>'AE',
                'iso2'=>'AE',
                'iso3'=>'ARE',
                'currency'=>'AED',
                'region'=>'Asia',
                'language'=>'Arabic',
                'capital'=>'Abu Dhabi',
                'latitude'=>24.4539,
                'longitude'=>54.3773,
                'flag'=>'https://flagcdn.com/w320/ae.png',
            ],

            [
                'name'=>'Australia',
                'code'=>'AU',
                'iso2'=>'AU',
                'iso3'=>'AUS',
                'currency'=>'AUD',
                'region'=>'Oceania',
                'language'=>'English',
                'capital'=>'Canberra',
                'latitude'=>-35.2809,
                'longitude'=>149.1300,
                'flag'=>'https://flagcdn.com/w320/au.png',
            ],

            [
                'name'=>'India',
                'code'=>'IN',
                'iso2'=>'IN',
                'iso3'=>'IND',
                'currency'=>'INR',
                'region'=>'Asia',
                'language'=>'Hindi, English',
                'capital'=>'New Delhi',
                'latitude'=>28.6139,
                'longitude'=>77.2090,
                'flag'=>'https://flagcdn.com/w320/in.png',
            ],

            [
                'name'=>'United Kingdom',
                'code'=>'GB',
                'iso2'=>'GB',
                'iso3'=>'GBR',
                'currency'=>'GBP',
                'region'=>'Europe',
                'language'=>'English',
                'capital'=>'London',
                'latitude'=>51.5074,
                'longitude'=>-0.1278,
                'flag'=>'https://flagcdn.com/w320/gb.png',
            ],

            [
                'name'=>'France',
                'code'=>'FR',
                'iso2'=>'FR',
                'iso3'=>'FRA',
                'currency'=>'EUR',
                'region'=>'Europe',
                'language'=>'French',
                'capital'=>'Paris',
                'latitude'=>48.8566,
                'longitude'=>2.3522,
                'flag'=>'https://flagcdn.com/w320/fr.png',
            ],

            [
                'name'=>'Italy',
                'code'=>'IT',
                'iso2'=>'IT',
                'iso3'=>'ITA',
                'currency'=>'EUR',
                'region'=>'Europe',
                'language'=>'Italian',
                'capital'=>'Rome',
                'latitude'=>41.9028,
                'longitude'=>12.4964,
                'flag'=>'https://flagcdn.com/w320/it.png',
            ],

            [
                'name'=>'Canada',
                'code'=>'CA',
                'iso2'=>'CA',
                'iso3'=>'CAN',
                'currency'=>'CAD',
                'region'=>'North America',
                'language'=>'English, French',
                'capital'=>'Ottawa',
                'latitude'=>45.4215,
                'longitude'=>-75.6972,
                'flag'=>'https://flagcdn.com/w320/ca.png',
            ],

            [
                'name'=>'Brazil',
                'code'=>'BR',
                'iso2'=>'BR',
                'iso3'=>'BRA',
                'currency'=>'BRL',
                'region'=>'South America',
                'language'=>'Portuguese',
                'capital'=>'Brasília',
                'latitude'=>-15.7939,
                'longitude'=>-47.8828,
                'flag'=>'https://flagcdn.com/w320/br.png',
            ],

            [
                'name'=>'Mexico',
                'code'=>'MX',
                'iso2'=>'MX',
                'iso3'=>'MEX',
                'currency'=>'MXN',
                'region'=>'North America',
                'language'=>'Spanish',
                'capital'=>'Mexico City',
                'latitude'=>19.4326,
                'longitude'=>-99.1332,
                'flag'=>'https://flagcdn.com/w320/mx.png',
            ],

            [
                'name'=>'Saudi Arabia',
                'code'=>'SA',
                'iso2'=>'SA',
                'iso3'=>'SAU',
                'currency'=>'SAR',
                'region'=>'Asia',
                'language'=>'Arabic',
                'capital'=>'Riyadh',
                'latitude'=>24.7136,
                'longitude'=>46.6753,
                'flag'=>'https://flagcdn.com/w320/sa.png',
            ],

            [
                'name'=>'Malaysia',
                'code'=>'MY',
                'iso2'=>'MY',
                'iso3'=>'MYS',
                'currency'=>'MYR',
                'region'=>'Asia',
                'language'=>'Malay',
                'capital'=>'Kuala Lumpur',
                'latitude'=>3.1390,
                'longitude'=>101.6869,
                'flag'=>'https://flagcdn.com/w320/my.png',
            ],

            [
                'name'=>'Thailand',
                'code'=>'TH',
                'iso2'=>'TH',
                'iso3'=>'THA',
                'currency'=>'THB',
                'region'=>'Asia',
                'language'=>'Thai',
                'capital'=>'Bangkok',
                'latitude'=>13.7563,
                'longitude'=>100.5018,
                'flag'=>'https://flagcdn.com/w320/th.png',
            ],

            [
                'name'=>'Taiwan',
                'code'=>'TW',
                'iso2'=>'TW',
                'iso3'=>'TWN',
                'currency'=>'TWD',
                'region'=>'Asia',
                'language'=>'Chinese',
                'capital'=>'Taipei',
                'latitude'=>25.0330,
                'longitude'=>121.5654,
                'flag'=>'https://flagcdn.com/w320/tw.png',
            ],

            [
                'name'=>'Denmark',
                'code'=>'DK',
                'iso2'=>'DK',
                'iso3'=>'DNK',
                'currency'=>'DKK',
                'region'=>'Europe',
                'language'=>'Danish',
                'capital'=>'Copenhagen',
                'latitude'=>55.6761,
                'longitude'=>12.5683,
                'flag'=>'https://flagcdn.com/w320/dk.png',
            ],

            [
                'name'=>'Israel',
                'code'=>'IL',
                'iso2'=>'IL',
                'iso3'=>'ISR',
                'currency'=>'ILS',
                'region'=>'Asia',
                'language'=>'Hebrew',
                'capital'=>'Jerusalem',
                'latitude'=>31.7683,
                'longitude'=>35.2137,
                'flag'=>'https://flagcdn.com/w320/il.png',
            ],

            [
                'name'=>'Hong Kong',
                'code'=>'HK',
                'iso2'=>'HK',
                'iso3'=>'HKG',
                'currency'=>'HKD',
                'region'=>'Asia',
                'language'=>'Chinese',
                'capital'=>'Hong Kong',
                'latitude'=>22.3193,
                'longitude'=>114.1694,
                'flag'=>'https://flagcdn.com/w320/hk.png',
            ],

            [
                'name'=>'South Africa',
                'code'=>'ZA',
                'iso2'=>'ZA',
                'iso3'=>'ZAF',
                'currency'=>'ZAR',
                'region'=>'Africa',
                'language'=>'English',
                'capital'=>'Pretoria',
                'latitude'=>-25.7479,
                'longitude'=>28.2293,
                'flag'=>'https://flagcdn.com/w320/za.png',
            ],

            [
'name'=>'Spain',
'code'=>'ES',
'iso2'=>'ES',
'iso3'=>'ESP',
'currency'=>'EUR',
'region'=>'Europe',
'language'=>'Spanish',
'capital'=>'Madrid',
'latitude'=>40.4168,
'longitude'=>-3.7038,
'flag'=>'https://flagcdn.com/w320/es.png',
],


[
'name'=>'Netherlands',
'code'=>'NL',
'iso2'=>'NL',
'iso3'=>'NLD',
'currency'=>'EUR',
'region'=>'Europe',
'language'=>'Dutch',
'capital'=>'Amsterdam',
'latitude'=>52.3676,
'longitude'=>4.9041,
'flag'=>'https://flagcdn.com/w320/nl.png',
],


[
'name'=>'Turkey',
'code'=>'TR',
'iso2'=>'TR',
'iso3'=>'TUR',
'currency'=>'TRY',
'region'=>'Asia',
'language'=>'Turkish',
'capital'=>'Ankara',
'latitude'=>39.9334,
'longitude'=>32.8597,
'flag'=>'https://flagcdn.com/w320/tr.png',
],


[
'name'=>'Vietnam',
'code'=>'VN',
'iso2'=>'VN',
'iso3'=>'VNM',
'currency'=>'VND',
'region'=>'Asia',
'language'=>'Vietnamese',
'capital'=>'Hanoi',
'latitude'=>21.0285,
'longitude'=>105.8542,
'flag'=>'https://flagcdn.com/w320/vn.png',
],


[
'name'=>'Philippines',
'code'=>'PH',
'iso2'=>'PH',
'iso3'=>'PHL',
'currency'=>'PHP',
'region'=>'Asia',
'language'=>'Filipino',
'capital'=>'Manila',
'latitude'=>14.5995,
'longitude'=>120.9842,
'flag'=>'https://flagcdn.com/w320/ph.png',
],


[
'name'=>'Russia',
'code'=>'RU',
'iso2'=>'RU',
'iso3'=>'RUS',
'currency'=>'RUB',
'region'=>'Europe',
'language'=>'Russian',
'capital'=>'Moscow',
'latitude'=>55.7558,
'longitude'=>37.6173,
'flag'=>'https://flagcdn.com/w320/ru.png',
],


[
'name'=>'Norway',
'code'=>'NO',
'iso2'=>'NO',
'iso3'=>'NOR',
'currency'=>'NOK',
'region'=>'Europe',
'language'=>'Norwegian',
'capital'=>'Oslo',
'latitude'=>59.9139,
'longitude'=>10.7522,
'flag'=>'https://flagcdn.com/w320/no.png',
],


[
'name'=>'Sweden',
'code'=>'SE',
'iso2'=>'SE',
'iso3'=>'SWE',
'currency'=>'SEK',
'region'=>'Europe',
'language'=>'Swedish',
'capital'=>'Stockholm',
'latitude'=>59.3293,
'longitude'=>18.0686,
'flag'=>'https://flagcdn.com/w320/se.png',
],


[
'name'=>'Switzerland',
'code'=>'CH',
'iso2'=>'CH',
'iso3'=>'CHE',
'currency'=>'CHF',
'region'=>'Europe',
'language'=>'German',
'capital'=>'Bern',
'latitude'=>46.9480,
'longitude'=>7.4474,
'flag'=>'https://flagcdn.com/w320/ch.png',
],


[
'name'=>'Poland',
'code'=>'PL',
'iso2'=>'PL',
'iso3'=>'POL',
'currency'=>'PLN',
'region'=>'Europe',
'language'=>'Polish',
'capital'=>'Warsaw',
'latitude'=>52.2297,
'longitude'=>21.0122,
'flag'=>'https://flagcdn.com/w320/pl.png',
],


[
'name'=>'Egypt',
'code'=>'EG',
'iso2'=>'EG',
'iso3'=>'EGY',
'currency'=>'EGP',
'region'=>'Africa',
'language'=>'Arabic',
'capital'=>'Cairo',
'latitude'=>30.0444,
'longitude'=>31.2357,
'flag'=>'https://flagcdn.com/w320/eg.png',
],


[
'name'=>'Nigeria',
'code'=>'NG',
'iso2'=>'NG',
'iso3'=>'NGA',
'currency'=>'NGN',
'region'=>'Africa',
'language'=>'English',
'capital'=>'Abuja',
'latitude'=>9.0765,
'longitude'=>7.3986,
'flag'=>'https://flagcdn.com/w320/ng.png',
],


[
'name'=>'Kenya',
'code'=>'KE',
'iso2'=>'KE',
'iso3'=>'KEN',
'currency'=>'KES',
'region'=>'Africa',
'language'=>'English',
'capital'=>'Nairobi',
'latitude'=>-1.2921,
'longitude'=>36.8219,
'flag'=>'https://flagcdn.com/w320/ke.png',
],


[
'name'=>'Argentina',
'code'=>'AR',
'iso2'=>'AR',
'iso3'=>'ARG',
'currency'=>'ARS',
'region'=>'South America',
'language'=>'Spanish',
'capital'=>'Buenos Aires',
'latitude'=>-34.6037,
'longitude'=>-58.3816,
'flag'=>'https://flagcdn.com/w320/ar.png',
],


[
'name'=>'Chile',
'code'=>'CL',
'iso2'=>'CL',
'iso3'=>'CHL',
'currency'=>'CLP',
'region'=>'South America',
'language'=>'Spanish',
'capital'=>'Santiago',
'latitude'=>-33.4489,
'longitude'=>-70.6693,
'flag'=>'https://flagcdn.com/w320/cl.png',
],


[
'name'=>'New Zealand',
'code'=>'NZ',
'iso2'=>'NZ',
'iso3'=>'NZL',
'currency'=>'NZD',
'region'=>'Oceania',
'language'=>'English',
'capital'=>'Wellington',
'latitude'=>-41.2865,
'longitude'=>174.7762,
'flag'=>'https://flagcdn.com/w320/nz.png',
],

[
'name'=>'Portugal',
'code'=>'PT',
'iso2'=>'PT',
'iso3'=>'PRT',
'currency'=>'EUR',
'region'=>'Europe',
'language'=>'Portuguese',
'capital'=>'Lisbon',
'latitude'=>38.7223,
'longitude'=>-9.1393,
'flag'=>'https://flagcdn.com/w320/pt.png',
],


[
'name'=>'Austria',
'code'=>'AT',
'iso2'=>'AT',
'iso3'=>'AUT',
'currency'=>'EUR',
'region'=>'Europe',
'language'=>'German',
'capital'=>'Vienna',
'latitude'=>48.2082,
'longitude'=>16.3738,
'flag'=>'https://flagcdn.com/w320/at.png',
],


[
'name'=>'Belgium',
'code'=>'BE',
'iso2'=>'BE',
'iso3'=>'BEL',
'currency'=>'EUR',
'region'=>'Europe',
'language'=>'Dutch, French',
'capital'=>'Brussels',
'latitude'=>50.8503,
'longitude'=>4.3517,
'flag'=>'https://flagcdn.com/w320/be.png',
],


[
'name'=>'Greece',
'code'=>'GR',
'iso2'=>'GR',
'iso3'=>'GRC',
'currency'=>'EUR',
'region'=>'Europe',
'language'=>'Greek',
'capital'=>'Athens',
'latitude'=>37.9838,
'longitude'=>23.7275,
'flag'=>'https://flagcdn.com/w320/gr.png',
],


[
'name'=>'Pakistan',
'code'=>'PK',
'iso2'=>'PK',
'iso3'=>'PAK',
'currency'=>'PKR',
'region'=>'Asia',
'language'=>'Urdu',
'capital'=>'Islamabad',
'latitude'=>33.6844,
'longitude'=>73.0479,
'flag'=>'https://flagcdn.com/w320/pk.png',
],


[
'name'=>'Bangladesh',
'code'=>'BD',
'iso2'=>'BD',
'iso3'=>'BGD',
'currency'=>'BDT',
'region'=>'Asia',
'language'=>'Bengali',
'capital'=>'Dhaka',
'latitude'=>23.8103,
'longitude'=>90.4125,
'flag'=>'https://flagcdn.com/w320/bd.png',
],


[
'name'=>'Qatar',
'code'=>'QA',
'iso2'=>'QA',
'iso3'=>'QAT',
'currency'=>'QAR',
'region'=>'Asia',
'language'=>'Arabic',
'capital'=>'Doha',
'latitude'=>25.2854,
'longitude'=>51.5310,
'flag'=>'https://flagcdn.com/w320/qa.png',
],


[
'name'=>'Vietnam',
'code'=>'VN',
'iso2'=>'VN',
'iso3'=>'VNM',
'currency'=>'VND',
'region'=>'Asia',
'language'=>'Vietnamese',
'capital'=>'Hanoi',
'latitude'=>21.0285,
'longitude'=>105.8542,
'flag'=>'https://flagcdn.com/w320/vn.png',
],


[
'name'=>'Colombia',
'code'=>'CO',
'iso2'=>'CO',
'iso3'=>'COL',
'currency'=>'COP',
'region'=>'South America',
'language'=>'Spanish',
'capital'=>'Bogota',
'latitude'=>4.7110,
'longitude'=>-74.0721,
'flag'=>'https://flagcdn.com/w320/co.png',
],


[
'name'=>'Peru',
'code'=>'PE',
'iso2'=>'PE',
'iso3'=>'PER',
'currency'=>'PEN',
'region'=>'South America',
'language'=>'Spanish',
'capital'=>'Lima',
'latitude'=>-12.0464,
'longitude'=>-77.0428,
'flag'=>'https://flagcdn.com/w320/pe.png',
],

[
'name'=>'Czech Republic',
'code'=>'CZ',
'iso2'=>'CZ',
'iso3'=>'CZE',
'currency'=>'CZK',
'region'=>'Europe',
'language'=>'Czech',
'capital'=>'Prague',
'latitude'=>50.0755,
'longitude'=>14.4378,
'flag'=>'https://flagcdn.com/w320/cz.png',
],


[
'name'=>'Finland',
'code'=>'FI',
'iso2'=>'FI',
'iso3'=>'FIN',
'currency'=>'EUR',
'region'=>'Europe',
'language'=>'Finnish',
'capital'=>'Helsinki',
'latitude'=>60.1699,
'longitude'=>24.9384,
'flag'=>'https://flagcdn.com/w320/fi.png',
],


[
'name'=>'Ireland',
'code'=>'IE',
'iso2'=>'IE',
'iso3'=>'IRL',
'currency'=>'EUR',
'region'=>'Europe',
'language'=>'English',
'capital'=>'Dublin',
'latitude'=>53.3498,
'longitude'=>-6.2603,
'flag'=>'https://flagcdn.com/w320/ie.png',
],


[
'name'=>'Ukraine',
'code'=>'UA',
'iso2'=>'UA',
'iso3'=>'UKR',
'currency'=>'UAH',
'region'=>'Europe',
'language'=>'Ukrainian',
'capital'=>'Kyiv',
'latitude'=>50.4501,
'longitude'=>30.5234,
'flag'=>'https://flagcdn.com/w320/ua.png',
],


[
'name'=>'Romania',
'code'=>'RO',
'iso2'=>'RO',
'iso3'=>'ROU',
'currency'=>'RON',
'region'=>'Europe',
'language'=>'Romanian',
'capital'=>'Bucharest',
'latitude'=>44.4268,
'longitude'=>26.1025,
'flag'=>'https://flagcdn.com/w320/ro.png',
],


[
'name'=>'Hungary',
'code'=>'HU',
'iso2'=>'HU',
'iso3'=>'HUN',
'currency'=>'HUF',
'region'=>'Europe',
'language'=>'Hungarian',
'capital'=>'Budapest',
'latitude'=>47.4979,
'longitude'=>19.0402,
'flag'=>'https://flagcdn.com/w320/hu.png',
],


[
'name'=>'Morocco',
'code'=>'MA',
'iso2'=>'MA',
'iso3'=>'MAR',
'currency'=>'MAD',
'region'=>'Africa',
'language'=>'Arabic',
'capital'=>'Rabat',
'latitude'=>34.0209,
'longitude'=>-6.8416,
'flag'=>'https://flagcdn.com/w320/ma.png',
],


[
'name'=>'Tunisia',
'code'=>'TN',
'iso2'=>'TN',
'iso3'=>'TUN',
'currency'=>'TND',
'region'=>'Africa',
'language'=>'Arabic',
'capital'=>'Tunis',
'latitude'=>36.8065,
'longitude'=>10.1815,
'flag'=>'https://flagcdn.com/w320/tn.png',
],


[
'name'=>'Ghana',
'code'=>'GH',
'iso2'=>'GH',
'iso3'=>'GHA',
'currency'=>'GHS',
'region'=>'Africa',
'language'=>'English',
'capital'=>'Accra',
'latitude'=>5.6037,
'longitude'=>-0.1870,
'flag'=>'https://flagcdn.com/w320/gh.png',
],


[
'name'=>'Ethiopia',
'code'=>'ET',
'iso2'=>'ET',
'iso3'=>'ETH',
'currency'=>'ETB',
'region'=>'Africa',
'language'=>'Amharic',
'capital'=>'Addis Ababa',
'latitude'=>9.0320,
'longitude'=>38.7469,
'flag'=>'https://flagcdn.com/w320/et.png',
],


[
'name'=>'Chile',
'code'=>'CL',
'iso2'=>'CL',
'iso3'=>'CHL',
'currency'=>'CLP',
'region'=>'South America',
'language'=>'Spanish',
'capital'=>'Santiago',
'latitude'=>-33.4489,
'longitude'=>-70.6693,
'flag'=>'https://flagcdn.com/w320/cl.png',
],


[
'name'=>'Uruguay',
'code'=>'UY',
'iso2'=>'UY',
'iso3'=>'URY',
'currency'=>'UYU',
'region'=>'South America',
'language'=>'Spanish',
'capital'=>'Montevideo',
'latitude'=>-34.9011,
'longitude'=>-56.1645,
'flag'=>'https://flagcdn.com/w320/uy.png',
],


[
'name'=>'Venezuela',
'code'=>'VE',
'iso2'=>'VE',
'iso3'=>'VEN',
'currency'=>'VES',
'region'=>'South America',
'language'=>'Spanish',
'capital'=>'Caracas',
'latitude'=>10.4806,
'longitude'=>-66.9036,
'flag'=>'https://flagcdn.com/w320/ve.png',
],


[
'name'=>'Ecuador',
'code'=>'EC',
'iso2'=>'EC',
'iso3'=>'ECU',
'currency'=>'USD',
'region'=>'South America',
'language'=>'Spanish',
'capital'=>'Quito',
'latitude'=>-0.1807,
'longitude'=>-78.4678,
'flag'=>'https://flagcdn.com/w320/ec.png',
],


[
'name'=>'Nigeria',
'code'=>'NG',
'iso2'=>'NG',
'iso3'=>'NGA',
'currency'=>'NGN',
'region'=>'Africa',
'language'=>'English',
'capital'=>'Abuja',
'latitude'=>9.0765,
'longitude'=>7.3986,
'flag'=>'https://flagcdn.com/w320/ng.png',
],

[
'name'=>'Pakistan',
'code'=>'PK',
'iso2'=>'PK',
'iso3'=>'PAK',
'currency'=>'PKR',
'region'=>'Asia',
'language'=>'Urdu',
'capital'=>'Islamabad',
'latitude'=>33.6844,
'longitude'=>73.0479,
'flag'=>'https://flagcdn.com/w320/pk.png',
],


[
'name'=>'Bangladesh',
'code'=>'BD',
'iso2'=>'BD',
'iso3'=>'BGD',
'currency'=>'BDT',
'region'=>'Asia',
'language'=>'Bengali',
'capital'=>'Dhaka',
'latitude'=>23.8103,
'longitude'=>90.4125,
'flag'=>'https://flagcdn.com/w320/bd.png',
],


[
'name'=>'Sri Lanka',
'code'=>'LK',
'iso2'=>'LK',
'iso3'=>'LKA',
'currency'=>'LKR',
'region'=>'Asia',
'language'=>'Sinhala',
'capital'=>'Sri Jayawardenepura Kotte',
'latitude'=>6.9271,
'longitude'=>79.8612,
'flag'=>'https://flagcdn.com/w320/lk.png',
],


[
'name'=>'Myanmar',
'code'=>'MM',
'iso2'=>'MM',
'iso3'=>'MMR',
'currency'=>'MMK',
'region'=>'Asia',
'language'=>'Burmese',
'capital'=>'Naypyidaw',
'latitude'=>19.7633,
'longitude'=>96.0785,
'flag'=>'https://flagcdn.com/w320/mm.png',
],


[
'name'=>'Cambodia',
'code'=>'KH',
'iso2'=>'KH',
'iso3'=>'KHM',
'currency'=>'KHR',
'region'=>'Asia',
'language'=>'Khmer',
'capital'=>'Phnom Penh',
'latitude'=>11.5564,
'longitude'=>104.9282,
'flag'=>'https://flagcdn.com/w320/kh.png',
],


[
'name'=>'Laos',
'code'=>'LA',
'iso2'=>'LA',
'iso3'=>'LAO',
'currency'=>'LAK',
'region'=>'Asia',
'language'=>'Lao',
'capital'=>'Vientiane',
'latitude'=>17.9757,
'longitude'=>102.6331,
'flag'=>'https://flagcdn.com/w320/la.png',
],


[
'name'=>'Mongolia',
'code'=>'MN',
'iso2'=>'MN',
'iso3'=>'MNG',
'currency'=>'MNT',
'region'=>'Asia',
'language'=>'Mongolian',
'capital'=>'Ulaanbaatar',
'latitude'=>47.8864,
'longitude'=>106.9057,
'flag'=>'https://flagcdn.com/w320/mn.png',
],


[
'name'=>'Kazakhstan',
'code'=>'KZ',
'iso2'=>'KZ',
'iso3'=>'KAZ',
'currency'=>'KZT',
'region'=>'Asia',
'language'=>'Kazakh',
'capital'=>'Astana',
'latitude'=>51.1694,
'longitude'=>71.4491,
'flag'=>'https://flagcdn.com/w320/kz.png',
],


[
'name'=>'Uzbekistan',
'code'=>'UZ',
'iso2'=>'UZ',
'iso3'=>'UZB',
'currency'=>'UZS',
'region'=>'Asia',
'language'=>'Uzbek',
'capital'=>'Tashkent',
'latitude'=>41.2995,
'longitude'=>69.2401,
'flag'=>'https://flagcdn.com/w320/uz.png',
],


[
'name'=>'Oman',
'code'=>'OM',
'iso2'=>'OM',
'iso3'=>'OMN',
'currency'=>'OMR',
'region'=>'Asia',
'language'=>'Arabic',
'capital'=>'Muscat',
'latitude'=>23.5880,
'longitude'=>58.3829,
'flag'=>'https://flagcdn.com/w320/om.png',
],


[
'name'=>'Kuwait',
'code'=>'KW',
'iso2'=>'KW',
'iso3'=>'KWT',
'currency'=>'KWD',
'region'=>'Asia',
'language'=>'Arabic',
'capital'=>'Kuwait City',
'latitude'=>29.3759,
'longitude'=>47.9774,
'flag'=>'https://flagcdn.com/w320/kw.png',
],


[
'name'=>'Bahrain',
'code'=>'BH',
'iso2'=>'BH',
'iso3'=>'BHR',
'currency'=>'BHD',
'region'=>'Asia',
'language'=>'Arabic',
'capital'=>'Manama',
'latitude'=>26.2235,
'longitude'=>50.5876,
'flag'=>'https://flagcdn.com/w320/bh.png',
],


[
'name'=>'Jordan',
'code'=>'JO',
'iso2'=>'JO',
'iso3'=>'JOR',
'currency'=>'JOD',
'region'=>'Asia',
'language'=>'Arabic',
'capital'=>'Amman',
'latitude'=>31.9539,
'longitude'=>35.9106,
'flag'=>'https://flagcdn.com/w320/jo.png',
],


[
'name'=>'Lebanon',
'code'=>'LB',
'iso2'=>'LB',
'iso3'=>'LBN',
'currency'=>'LBP',
'region'=>'Asia',
'language'=>'Arabic',
'capital'=>'Beirut',
'latitude'=>33.8938,
'longitude'=>35.5018,
'flag'=>'https://flagcdn.com/w320/lb.png',
],


[
'name'=>'Iraq',
'code'=>'IQ',
'iso2'=>'IQ',
'iso3'=>'IRQ',
'currency'=>'IQD',
'region'=>'Asia',
'language'=>'Arabic',
'capital'=>'Baghdad',
'latitude'=>33.3152,
'longitude'=>44.3661,
'flag'=>'https://flagcdn.com/w320/iq.png',
],


[
'name'=>'Iran',
'code'=>'IR',
'iso2'=>'IR',
'iso3'=>'IRN',
'currency'=>'IRR',
'region'=>'Asia',
'language'=>'Persian',
'capital'=>'Tehran',
'latitude'=>35.6892,
'longitude'=>51.3890,
'flag'=>'https://flagcdn.com/w320/ir.png',
],


[
'name'=>'Afghanistan',
'code'=>'AF',
'iso2'=>'AF',
'iso3'=>'AFG',
'currency'=>'AFN',
'region'=>'Asia',
'language'=>'Pashto',
'capital'=>'Kabul',
'latitude'=>34.5553,
'longitude'=>69.2075,
'flag'=>'https://flagcdn.com/w320/af.png',
],


[
'name'=>'Nepal',
'code'=>'NP',
'iso2'=>'NP',
'iso3'=>'NPL',
'currency'=>'NPR',
'region'=>'Asia',
'language'=>'Nepali',
'capital'=>'Kathmandu',
'latitude'=>27.7172,
'longitude'=>85.3240,
'flag'=>'https://flagcdn.com/w320/np.png',
],


[
'name'=>'Fiji',
'code'=>'FJ',
'iso2'=>'FJ',
'iso3'=>'FJI',
'currency'=>'FJD',
'region'=>'Oceania',
'language'=>'English',
'capital'=>'Suva',
'latitude'=>-18.1248,
'longitude'=>178.4501,
'flag'=>'https://flagcdn.com/w320/fj.png',
],


[
'name'=>'Papua New Guinea',
'code'=>'PG',
'iso2'=>'PG',
'iso3'=>'PNG',
'currency'=>'PGK',
'region'=>'Oceania',
'language'=>'English',
'capital'=>'Port Moresby',
'latitude'=>-9.4438,
'longitude'=>147.1803,
'flag'=>'https://flagcdn.com/w320/pg.png',
],


[
'name'=>'Costa Rica',
'code'=>'CR',
'iso2'=>'CR',
'iso3'=>'CRI',
'currency'=>'CRC',
'region'=>'North America',
'language'=>'Spanish',
'capital'=>'San Jose',
'latitude'=>9.9281,
'longitude'=>-84.0907,
'flag'=>'https://flagcdn.com/w320/cr.png',
],


[
'name'=>'Panama',
'code'=>'PA',
'iso2'=>'PA',
'iso3'=>'PAN',
'currency'=>'PAB',
'region'=>'North America',
'language'=>'Spanish',
'capital'=>'Panama City',
'latitude'=>8.9824,
'longitude'=>-79.5199,
'flag'=>'https://flagcdn.com/w320/pa.png',
],


[
'name'=>'Guatemala',
'code'=>'GT',
'iso2'=>'GT',
'iso3'=>'GTM',
'currency'=>'GTQ',
'region'=>'North America',
'language'=>'Spanish',
'capital'=>'Guatemala City',
'latitude'=>14.6349,
'longitude'=>-90.5069,
'flag'=>'https://flagcdn.com/w320/gt.png',
],


[
'name'=>'Dominican Republic',
'code'=>'DO',
'iso2'=>'DO',
'iso3'=>'DOM',
'currency'=>'DOP',
'region'=>'North America',
'language'=>'Spanish',
'capital'=>'Santo Domingo',
'latitude'=>18.4861,
'longitude'=>-69.9312,
'flag'=>'https://flagcdn.com/w320/do.png',
],


[
'name'=>'Cuba',
'code'=>'CU',
'iso2'=>'CU',
'iso3'=>'CUB',
'currency'=>'CUP',
'region'=>'North America',
'language'=>'Spanish',
'capital'=>'Havana',
'latitude'=>23.1136,
'longitude'=>-82.3666,
'flag'=>'https://flagcdn.com/w320/cu.png',
],


[
'name'=>'Jamaica',
'code'=>'JM',
'iso2'=>'JM',
'iso3'=>'JAM',
'currency'=>'JMD',
'region'=>'North America',
'language'=>'English',
'capital'=>'Kingston',
'latitude'=>17.9712,
'longitude'=>-76.7936,
'flag'=>'https://flagcdn.com/w320/jm.png',
],


[
'name'=>'Bolivia',
'code'=>'BO',
'iso2'=>'BO',
'iso3'=>'BOL',
'currency'=>'BOB',
'region'=>'South America',
'language'=>'Spanish',
'capital'=>'La Paz',
'latitude'=>-16.4897,
'longitude'=>-68.1193,
'flag'=>'https://flagcdn.com/w320/bo.png',
],


[
'name'=>'Paraguay',
'code'=>'PY',
'iso2'=>'PY',
'iso3'=>'PRY',
'currency'=>'PYG',
'region'=>'South America',
'language'=>'Spanish',
'capital'=>'Asuncion',
'latitude'=>-25.2637,
'longitude'=>-57.5759,
'flag'=>'https://flagcdn.com/w320/py.png',
],


[
'name'=>'Ecuador',
'code'=>'EC',
'iso2'=>'EC',
'iso3'=>'ECU',
'currency'=>'USD',
'region'=>'South America',
'language'=>'Spanish',
'capital'=>'Quito',
'latitude'=>-0.1807,
'longitude'=>-78.4678,
'flag'=>'https://flagcdn.com/w320/ec.png',
],


[
'name'=>'Trinidad and Tobago',
'code'=>'TT',
'iso2'=>'TT',
'iso3'=>'TTO',
'currency'=>'TTD',
'region'=>'North America',
'language'=>'English',
'capital'=>'Port of Spain',
'latitude'=>10.6549,
'longitude'=>-61.5019,
'flag'=>'https://flagcdn.com/w320/tt.png',
],


[
'name'=>'Malta',
'code'=>'MT',
'iso2'=>'MT',
'iso3'=>'MLT',
'currency'=>'EUR',
'region'=>'Europe',
'language'=>'Maltese',
'capital'=>'Valletta',
'latitude'=>35.8997,
'longitude'=>14.5147,
'flag'=>'https://flagcdn.com/w320/mt.png',
],


[
'name'=>'Iceland',
'code'=>'IS',
'iso2'=>'IS',
'iso3'=>'ISL',
'currency'=>'ISK',
'region'=>'Europe',
'language'=>'Icelandic',
'capital'=>'Reykjavik',
'latitude'=>64.1466,
'longitude'=>-21.9426,
'flag'=>'https://flagcdn.com/w320/is.png',
],


[
'name'=>'Slovakia',
'code'=>'SK',
'iso2'=>'SK',
'iso3'=>'SVK',
'currency'=>'EUR',
'region'=>'Europe',
'language'=>'Slovak',
'capital'=>'Bratislava',
'latitude'=>48.1486,
'longitude'=>17.1077,
'flag'=>'https://flagcdn.com/w320/sk.png',
],

[
'name'=>'Algeria',
'code'=>'DZ',
'iso2'=>'DZ',
'iso3'=>'DZA',
'currency'=>'DZD',
'region'=>'Africa',
'language'=>'Arabic',
'capital'=>'Algiers',
'latitude'=>36.7538,
'longitude'=>3.0588,
'flag'=>'https://flagcdn.com/w320/dz.png',
],


[
'name'=>'Angola',
'code'=>'AO',
'iso2'=>'AO',
'iso3'=>'AGO',
'currency'=>'AOA',
'region'=>'Africa',
'language'=>'Portuguese',
'capital'=>'Luanda',
'latitude'=>-8.8390,
'longitude'=>13.2894,
'flag'=>'https://flagcdn.com/w320/ao.png',
],


[
'name'=>'Botswana',
'code'=>'BW',
'iso2'=>'BW',
'iso3'=>'BWA',
'currency'=>'BWP',
'region'=>'Africa',
'language'=>'English',
'capital'=>'Gaborone',
'latitude'=>-24.6282,
'longitude'=>25.9231,
'flag'=>'https://flagcdn.com/w320/bw.png',
],


[
'name'=>'Cameroon',
'code'=>'CM',
'iso2'=>'CM',
'iso3'=>'CMR',
'currency'=>'XAF',
'region'=>'Africa',
'language'=>'French',
'capital'=>'Yaounde',
'latitude'=>3.8480,
'longitude'=>11.5021,
'flag'=>'https://flagcdn.com/w320/cm.png',
],


[
'name'=>'Ivory Coast',
'code'=>'CI',
'iso2'=>'CI',
'iso3'=>'CIV',
'currency'=>'XOF',
'region'=>'Africa',
'language'=>'French',
'capital'=>'Yamoussoukro',
'latitude'=>6.8276,
'longitude'=>-5.2893,
'flag'=>'https://flagcdn.com/w320/ci.png',
],


[
'name'=>'Madagascar',
'code'=>'MG',
'iso2'=>'MG',
'iso3'=>'MDG',
'currency'=>'MGA',
'region'=>'Africa',
'language'=>'Malagasy',
'capital'=>'Antananarivo',
'latitude'=>-18.8792,
'longitude'=>47.5079,
'flag'=>'https://flagcdn.com/w320/mg.png',
],


[
'name'=>'Mauritius',
'code'=>'MU',
'iso2'=>'MU',
'iso3'=>'MUS',
'currency'=>'MUR',
'region'=>'Africa',
'language'=>'English',
'capital'=>'Port Louis',
'latitude'=>-20.1609,
'longitude'=>57.5012,
'flag'=>'https://flagcdn.com/w320/mu.png',
],


[
'name'=>'Namibia',
'code'=>'NA',
'iso2'=>'NA',
'iso3'=>'NAM',
'currency'=>'NAD',
'region'=>'Africa',
'language'=>'English',
'capital'=>'Windhoek',
'latitude'=>-22.5609,
'longitude'=>17.0658,
'flag'=>'https://flagcdn.com/w320/na.png',
],


[
'name'=>'Senegal',
'code'=>'SN',
'iso2'=>'SN',
'iso3'=>'SEN',
'currency'=>'XOF',
'region'=>'Africa',
'language'=>'French',
'capital'=>'Dakar',
'latitude'=>14.7167,
'longitude'=>-17.4677,
'flag'=>'https://flagcdn.com/w320/sn.png',
],


[
'name'=>'Tanzania',
'code'=>'TZ',
'iso2'=>'TZ',
'iso3'=>'TZA',
'currency'=>'TZS',
'region'=>'Africa',
'language'=>'Swahili',
'capital'=>'Dodoma',
'latitude'=>-6.1630,
'longitude'=>35.7516,
'flag'=>'https://flagcdn.com/w320/tz.png',
],


[
'name'=>'Uganda',
'code'=>'UG',
'iso2'=>'UG',
'iso3'=>'UGA',
'currency'=>'UGX',
'region'=>'Africa',
'language'=>'English',
'capital'=>'Kampala',
'latitude'=>0.3476,
'longitude'=>32.5825,
'flag'=>'https://flagcdn.com/w320/ug.png',
],


[
'name'=>'Zimbabwe',
'code'=>'ZW',
'iso2'=>'ZW',
'iso3'=>'ZWE',
'currency'=>'ZWL',
'region'=>'Africa',
'language'=>'English',
'capital'=>'Harare',
'latitude'=>-17.8252,
'longitude'=>31.0335,
'flag'=>'https://flagcdn.com/w320/zw.png',
],


[
'name'=>'Belarus',
'code'=>'BY',
'iso2'=>'BY',
'iso3'=>'BLR',
'currency'=>'BYN',
'region'=>'Europe',
'language'=>'Belarusian',
'capital'=>'Minsk',
'latitude'=>53.9006,
'longitude'=>27.5590,
'flag'=>'https://flagcdn.com/w320/by.png',
],


[
'name'=>'Bulgaria',
'code'=>'BG',
'iso2'=>'BG',
'iso3'=>'BGR',
'currency'=>'BGN',
'region'=>'Europe',
'language'=>'Bulgarian',
'capital'=>'Sofia',
'latitude'=>42.6977,
'longitude'=>23.3219,
'flag'=>'https://flagcdn.com/w320/bg.png',
],


[
'name'=>'Croatia',
'code'=>'HR',
'iso2'=>'HR',
'iso3'=>'HRV',
'currency'=>'EUR',
'region'=>'Europe',
'language'=>'Croatian',
'capital'=>'Zagreb',
'latitude'=>45.8150,
'longitude'=>15.9819,
'flag'=>'https://flagcdn.com/w320/hr.png',
],


[
'name'=>'Denmark',
'code'=>'DK',
'iso2'=>'DK',
'iso3'=>'DNK',
'currency'=>'DKK',
'region'=>'Europe',
'language'=>'Danish',
'capital'=>'Copenhagen',
'latitude'=>55.6761,
'longitude'=>12.5683,
'flag'=>'https://flagcdn.com/w320/dk.png',
],


[
'name'=>'Estonia',
'code'=>'EE',
'iso2'=>'EE',
'iso3'=>'EST',
'currency'=>'EUR',
'region'=>'Europe',
'language'=>'Estonian',
'capital'=>'Tallinn',
'latitude'=>59.4370,
'longitude'=>24.7536,
'flag'=>'https://flagcdn.com/w320/ee.png',
],


[
'name'=>'Lithuania',
'code'=>'LT',
'iso2'=>'LT',
'iso3'=>'LTU',
'currency'=>'EUR',
'region'=>'Europe',
'language'=>'Lithuanian',
'capital'=>'Vilnius',
'latitude'=>54.6872,
'longitude'=>25.2797,
'flag'=>'https://flagcdn.com/w320/lt.png',
],


[
'name'=>'Luxembourg',
'code'=>'LU',
'iso2'=>'LU',
'iso3'=>'LUX',
'currency'=>'EUR',
'region'=>'Europe',
'language'=>'Luxembourgish',
'capital'=>'Luxembourg',
'latitude'=>49.6116,
'longitude'=>6.1319,
'flag'=>'https://flagcdn.com/w320/lu.png',
],


[
'name'=>'Serbia',
'code'=>'RS',
'iso2'=>'RS',
'iso3'=>'SRB',
'currency'=>'RSD',
'region'=>'Europe',
'language'=>'Serbian',
'capital'=>'Belgrade',
'latitude'=>44.7866,
'longitude'=>20.4489,
'flag'=>'https://flagcdn.com/w320/rs.png',
],

[
'name'=>'Japan',
'code'=>'JP',
'iso2'=>'JP',
'iso3'=>'JPN',
'currency'=>'JPY',
'region'=>'Asia',
'language'=>'Japanese',
'capital'=>'Tokyo',
'latitude'=>35.6762,
'longitude'=>139.6503,
'flag'=>'https://flagcdn.com/w320/jp.png',
],


[
'name'=>'South Korea',
'code'=>'KR',
'iso2'=>'KR',
'iso3'=>'KOR',
'currency'=>'KRW',
'region'=>'Asia',
'language'=>'Korean',
'capital'=>'Seoul',
'latitude'=>37.5665,
'longitude'=>126.9780,
'flag'=>'https://flagcdn.com/w320/kr.png',
],


[
'name'=>'Taiwan',
'code'=>'TW',
'iso2'=>'TW',
'iso3'=>'TWN',
'currency'=>'TWD',
'region'=>'Asia',
'language'=>'Chinese',
'capital'=>'Taipei',
'latitude'=>25.0330,
'longitude'=>121.5654,
'flag'=>'https://flagcdn.com/w320/tw.png',
],


[
'name'=>'Hong Kong',
'code'=>'HK',
'iso2'=>'HK',
'iso3'=>'HKG',
'currency'=>'HKD',
'region'=>'Asia',
'language'=>'Chinese',
'capital'=>'Hong Kong',
'latitude'=>22.3193,
'longitude'=>114.1694,
'flag'=>'https://flagcdn.com/w320/hk.png',
],


[
'name'=>'Macau',
'code'=>'MO',
'iso2'=>'MO',
'iso3'=>'MAC',
'currency'=>'MOP',
'region'=>'Asia',
'language'=>'Chinese',
'capital'=>'Macau',
'latitude'=>22.1987,
'longitude'=>113.5439,
'flag'=>'https://flagcdn.com/w320/mo.png',
],


[
'name'=>'Brunei',
'code'=>'BN',
'iso2'=>'BN',
'iso3'=>'BRN',
'currency'=>'BND',
'region'=>'Asia',
'language'=>'Malay',
'capital'=>'Bandar Seri Begawan',
'latitude'=>4.9031,
'longitude'=>114.9398,
'flag'=>'https://flagcdn.com/w320/bn.png',
],


[
'name'=>'Timor-Leste',
'code'=>'TL',
'iso2'=>'TL',
'iso3'=>'TLS',
'currency'=>'USD',
'region'=>'Asia',
'language'=>'Portuguese',
'capital'=>'Dili',
'latitude'=>-8.5569,
'longitude'=>125.5603,
'flag'=>'https://flagcdn.com/w320/tl.png',
],


[
'name'=>'Maldives',
'code'=>'MV',
'iso2'=>'MV',
'iso3'=>'MDV',
'currency'=>'MVR',
'region'=>'Asia',
'language'=>'Dhivehi',
'capital'=>'Male',
'latitude'=>4.1755,
'longitude'=>73.5093,
'flag'=>'https://flagcdn.com/w320/mv.png',
],


[
'name'=>'Bhutan',
'code'=>'BT',
'iso2'=>'BT',
'iso3'=>'BTN',
'currency'=>'BTN',
'region'=>'Asia',
'language'=>'Dzongkha',
'capital'=>'Thimphu',
'latitude'=>27.4728,
'longitude'=>89.6390,
'flag'=>'https://flagcdn.com/w320/bt.png',
],


[
'name'=>'Armenia',
'code'=>'AM',
'iso2'=>'AM',
'iso3'=>'ARM',
'currency'=>'AMD',
'region'=>'Asia',
'language'=>'Armenian',
'capital'=>'Yerevan',
'latitude'=>40.1792,
'longitude'=>44.4991,
'flag'=>'https://flagcdn.com/w320/am.png',
],


[
'name'=>'Azerbaijan',
'code'=>'AZ',
'iso2'=>'AZ',
'iso3'=>'AZE',
'currency'=>'AZN',
'region'=>'Asia',
'language'=>'Azerbaijani',
'capital'=>'Baku',
'latitude'=>40.4093,
'longitude'=>49.8671,
'flag'=>'https://flagcdn.com/w320/az.png',
],


[
'name'=>'Georgia',
'code'=>'GE',
'iso2'=>'GE',
'iso3'=>'GEO',
'currency'=>'GEL',
'region'=>'Asia',
'language'=>'Georgian',
'capital'=>'Tbilisi',
'latitude'=>41.7151,
'longitude'=>44.8271,
'flag'=>'https://flagcdn.com/w320/ge.png',
],


[
'name'=>'Moldova',
'code'=>'MD',
'iso2'=>'MD',
'iso3'=>'MDA',
'currency'=>'MDL',
'region'=>'Europe',
'language'=>'Romanian',
'capital'=>'Chisinau',
'latitude'=>47.0105,
'longitude'=>28.8638,
'flag'=>'https://flagcdn.com/w320/md.png',
],


[
'name'=>'Slovenia',
'code'=>'SI',
'iso2'=>'SI',
'iso3'=>'SVN',
'currency'=>'EUR',
'region'=>'Europe',
'language'=>'Slovenian',
'capital'=>'Ljubljana',
'latitude'=>46.0569,
'longitude'=>14.5058,
'flag'=>'https://flagcdn.com/w320/si.png',
],


[
'name'=>'Bosnia and Herzegovina',
'code'=>'BA',
'iso2'=>'BA',
'iso3'=>'BIH',
'currency'=>'BAM',
'region'=>'Europe',
'language'=>'Bosnian',
'capital'=>'Sarajevo',
'latitude'=>43.8563,
'longitude'=>18.4131,
'flag'=>'https://flagcdn.com/w320/ba.png',
],


[
'name'=>'Albania',
'code'=>'AL',
'iso2'=>'AL',
'iso3'=>'ALB',
'currency'=>'ALL',
'region'=>'Europe',
'language'=>'Albanian',
'capital'=>'Tirana',
'latitude'=>41.3275,
'longitude'=>19.8187,
'flag'=>'https://flagcdn.com/w320/al.png',
],


[
'name'=>'North Macedonia',
'code'=>'MK',
'iso2'=>'MK',
'iso3'=>'MKD',
'currency'=>'MKD',
'region'=>'Europe',
'language'=>'Macedonian',
'capital'=>'Skopje',
'latitude'=>41.9981,
'longitude'=>21.4254,
'flag'=>'https://flagcdn.com/w320/mk.png',
],


[
'name'=>'Cyprus',
'code'=>'CY',
'iso2'=>'CY',
'iso3'=>'CYP',
'currency'=>'EUR',
'region'=>'Europe',
'language'=>'Greek',
'capital'=>'Nicosia',
'latitude'=>35.1856,
'longitude'=>33.3823,
'flag'=>'https://flagcdn.com/w320/cy.png',
],


[
'name'=>'Montenegro',
'code'=>'ME',
'iso2'=>'ME',
'iso3'=>'MNE',
'currency'=>'EUR',
'region'=>'Europe',
'language'=>'Montenegrin',
'capital'=>'Podgorica',
'latitude'=>42.4304,
'longitude'=>19.2594,
'flag'=>'https://flagcdn.com/w320/me.png',
],


[
'name'=>'Honduras',
'code'=>'HN',
'iso2'=>'HN',
'iso3'=>'HND',
'currency'=>'HNL',
'region'=>'North America',
'language'=>'Spanish',
'capital'=>'Tegucigalpa',
'latitude'=>14.0723,
'longitude'=>-87.1921,
'flag'=>'https://flagcdn.com/w320/hn.png',
],


[
'name'=>'El Salvador',
'code'=>'SV',
'iso2'=>'SV',
'iso3'=>'SLV',
'currency'=>'USD',
'region'=>'North America',
'language'=>'Spanish',
'capital'=>'San Salvador',
'latitude'=>13.6929,
'longitude'=>-89.2182,
'flag'=>'https://flagcdn.com/w320/sv.png',
],


[
'name'=>'Nicaragua',
'code'=>'NI',
'iso2'=>'NI',
'iso3'=>'NIC',
'currency'=>'NIO',
'region'=>'North America',
'language'=>'Spanish',
'capital'=>'Managua',
'latitude'=>12.1150,
'longitude'=>-86.2362,
'flag'=>'https://flagcdn.com/w320/ni.png',
],


[
'name'=>'Belize',
'code'=>'BZ',
'iso2'=>'BZ',
'iso3'=>'BLZ',
'currency'=>'BZD',
'region'=>'North America',
'language'=>'English',
'capital'=>'Belmopan',
'latitude'=>17.2510,
'longitude'=>-88.7590,
'flag'=>'https://flagcdn.com/w320/bz.png',
],


[
'name'=>'Guyana',
'code'=>'GY',
'iso2'=>'GY',
'iso3'=>'GUY',
'currency'=>'GYD',
'region'=>'South America',
'language'=>'English',
'capital'=>'Georgetown',
'latitude'=>6.8013,
'longitude'=>-58.1551,
'flag'=>'https://flagcdn.com/w320/gy.png',
],

[
'name'=>'Canada',
'code'=>'CA',
'iso2'=>'CA',
'iso3'=>'CAN',
'currency'=>'CAD',
'region'=>'North America',
'language'=>'English',
'capital'=>'Ottawa',
'latitude'=>45.4215,
'longitude'=>-75.6972,
'flag'=>'https://flagcdn.com/w320/ca.png',
],


[
'name'=>'United States',
'code'=>'US',
'iso2'=>'US',
'iso3'=>'USA',
'currency'=>'USD',
'region'=>'North America',
'language'=>'English',
'capital'=>'Washington DC',
'latitude'=>38.9072,
'longitude'=>-77.0369,
'flag'=>'https://flagcdn.com/w320/us.png',
],


[
'name'=>'Mexico',
'code'=>'MX',
'iso2'=>'MX',
'iso3'=>'MEX',
'currency'=>'MXN',
'region'=>'North America',
'language'=>'Spanish',
'capital'=>'Mexico City',
'latitude'=>19.4326,
'longitude'=>-99.1332,
'flag'=>'https://flagcdn.com/w320/mx.png',
],


[
'name'=>'Australia',
'code'=>'AU',
'iso2'=>'AU',
'iso3'=>'AUS',
'currency'=>'AUD',
'region'=>'Oceania',
'language'=>'English',
'capital'=>'Canberra',
'latitude'=>-35.2809,
'longitude'=>149.1300,
'flag'=>'https://flagcdn.com/w320/au.png',
],


[
'name'=>'Samoa',
'code'=>'WS',
'iso2'=>'WS',
'iso3'=>'WSM',
'currency'=>'WST',
'region'=>'Oceania',
'language'=>'Samoan',
'capital'=>'Apia',
'latitude'=>-13.8333,
'longitude'=>-171.7667,
'flag'=>'https://flagcdn.com/w320/ws.png',
],


[
'name'=>'Tonga',
'code'=>'TO',
'iso2'=>'TO',
'iso3'=>'TON',
'currency'=>'TOP',
'region'=>'Oceania',
'language'=>'Tongan',
'capital'=>'Nuku’alofa',
'latitude'=>-21.1394,
'longitude'=>-175.2049,
'flag'=>'https://flagcdn.com/w320/to.png',
],


[
'name'=>'Vanuatu',
'code'=>'VU',
'iso2'=>'VU',
'iso3'=>'VUT',
'currency'=>'VUV',
'region'=>'Oceania',
'language'=>'Bislama',
'capital'=>'Port Vila',
'latitude'=>-17.7333,
'longitude'=>168.3273,
'flag'=>'https://flagcdn.com/w320/vu.png',
],


[
'name'=>'Solomon Islands',
'code'=>'SB',
'iso2'=>'SB',
'iso3'=>'SLB',
'currency'=>'SBD',
'region'=>'Oceania',
'language'=>'English',
'capital'=>'Honiara',
'latitude'=>-9.4438,
'longitude'=>159.9729,
'flag'=>'https://flagcdn.com/w320/sb.png',
],


[
'name'=>'Palau',
'code'=>'PW',
'iso2'=>'PW',
'iso3'=>'PLW',
'currency'=>'USD',
'region'=>'Oceania',
'language'=>'Palauan',
'capital'=>'Ngerulmud',
'latitude'=>7.5000,
'longitude'=>134.6242,
'flag'=>'https://flagcdn.com/w320/pw.png',
],


[
'name'=>'Marshall Islands',
'code'=>'MH',
'iso2'=>'MH',
'iso3'=>'MHL',
'currency'=>'USD',
'region'=>'Oceania',
'language'=>'Marshallese',
'capital'=>'Majuro',
'latitude'=>7.1164,
'longitude'=>171.1858,
'flag'=>'https://flagcdn.com/w320/mh.png',
],


[
'name'=>'South Africa',
'code'=>'ZA',
'iso2'=>'ZA',
'iso3'=>'ZAF',
'currency'=>'ZAR',
'region'=>'Africa',
'language'=>'English',
'capital'=>'Pretoria',
'latitude'=>-25.7479,
'longitude'=>28.2293,
'flag'=>'https://flagcdn.com/w320/za.png',
],


[
'name'=>'Sudan',
'code'=>'SD',
'iso2'=>'SD',
'iso3'=>'SDN',
'currency'=>'SDG',
'region'=>'Africa',
'language'=>'Arabic',
'capital'=>'Khartoum',
'latitude'=>15.5007,
'longitude'=>32.5599,
'flag'=>'https://flagcdn.com/w320/sd.png',
],


[
'name'=>'Rwanda',
'code'=>'RW',
'iso2'=>'RW',
'iso3'=>'RWA',
'currency'=>'RWF',
'region'=>'Africa',
'language'=>'Kinyarwanda',
'capital'=>'Kigali',
'latitude'=>-1.9441,
'longitude'=>30.0619,
'flag'=>'https://flagcdn.com/w320/rw.png',
],


[
'name'=>'Zambia',
'code'=>'ZM',
'iso2'=>'ZM',
'iso3'=>'ZMB',
'currency'=>'ZMW',
'region'=>'Africa',
'language'=>'English',
'capital'=>'Lusaka',
'latitude'=>-15.3875,
'longitude'=>28.3228,
'flag'=>'https://flagcdn.com/w320/zm.png',
],


[
'name'=>'Mozambique',
'code'=>'MZ',
'iso2'=>'MZ',
'iso3'=>'MOZ',
'currency'=>'MZN',
'region'=>'Africa',
'language'=>'Portuguese',
'capital'=>'Maputo',
'latitude'=>-25.9692,
'longitude'=>32.5732,
'flag'=>'https://flagcdn.com/w320/mz.png',
],


[
'name'=>'Malawi',
'code'=>'MW',
'iso2'=>'MW',
'iso3'=>'MWI',
'currency'=>'MWK',
'region'=>'Africa',
'language'=>'English',
'capital'=>'Lilongwe',
'latitude'=>-13.9626,
'longitude'=>33.7741,
'flag'=>'https://flagcdn.com/w320/mw.png',
],


[
'name'=>'Burundi',
'code'=>'BI',
'iso2'=>'BI',
'iso3'=>'BDI',
'currency'=>'BIF',
'region'=>'Africa',
'language'=>'French',
'capital'=>'Gitega',
'latitude'=>-3.4264,
'longitude'=>29.9308,
'flag'=>'https://flagcdn.com/w320/bi.png',
],


[
'name'=>'Seychelles',
'code'=>'SC',
'iso2'=>'SC',
'iso3'=>'SYC',
'currency'=>'SCR',
'region'=>'Africa',
'language'=>'English',
'capital'=>'Victoria',
'latitude'=>-4.6191,
'longitude'=>55.4513,
'flag'=>'https://flagcdn.com/w320/sc.png',
],


[
'name'=>'Libya',
'code'=>'LY',
'iso2'=>'LY',
'iso3'=>'LBY',
'currency'=>'LYD',
'region'=>'Africa',
'language'=>'Arabic',
'capital'=>'Tripoli',
'latitude'=>32.8872,
'longitude'=>13.1913,
'flag'=>'https://flagcdn.com/w320/ly.png',
],


[
'name'=>'Somalia',
'code'=>'SO',
'iso2'=>'SO',
'iso3'=>'SOM',
'currency'=>'SOS',
'region'=>'Africa',
'language'=>'Somali',
'capital'=>'Mogadishu',
'latitude'=>2.0469,
'longitude'=>45.3182,
'flag'=>'https://flagcdn.com/w320/so.png',
],


[
'name'=>'Yemen',
'code'=>'YE',
'iso2'=>'YE',
'iso3'=>'YEM',
'currency'=>'YER',
'region'=>'Asia',
'language'=>'Arabic',
'capital'=>'Sana’a',
'latitude'=>15.3694,
'longitude'=>44.1910,
'flag'=>'https://flagcdn.com/w320/ye.png',
],


[
'name'=>'Syria',
'code'=>'SY',
'iso2'=>'SY',
'iso3'=>'SYR',
'currency'=>'SYP',
'region'=>'Asia',
'language'=>'Arabic',
'capital'=>'Damascus',
'latitude'=>33.5138,
'longitude'=>36.2765,
'flag'=>'https://flagcdn.com/w320/sy.png',
],


[
'name'=>'Israel',
'code'=>'IL',
'iso2'=>'IL',
'iso3'=>'ISR',
'currency'=>'ILS',
'region'=>'Asia',
'language'=>'Hebrew',
'capital'=>'Jerusalem',
'latitude'=>31.7683,
'longitude'=>35.2137,
'flag'=>'https://flagcdn.com/w320/il.png',
],


[
'name'=>'Kyrgyzstan',
'code'=>'KG',
'iso2'=>'KG',
'iso3'=>'KGZ',
'currency'=>'KGS',
'region'=>'Asia',
'language'=>'Kyrgyz',
'capital'=>'Bishkek',
'latitude'=>42.8746,
'longitude'=>74.5698,
'flag'=>'https://flagcdn.com/w320/kg.png',
],


[
'name'=>'Tajikistan',
'code'=>'TJ',
'iso2'=>'TJ',
'iso3'=>'TJK',
'currency'=>'TJS',
'region'=>'Asia',
'language'=>'Tajik',
'capital'=>'Dushanbe',
'latitude'=>38.5598,
'longitude'=>68.7870,
'flag'=>'https://flagcdn.com/w320/tj.png',
],


[
'name'=>'Turkmenistan',
'code'=>'TM',
'iso2'=>'TM',
'iso3'=>'TKM',
'currency'=>'TMT',
'region'=>'Asia',
'language'=>'Turkmen',
'capital'=>'Ashgabat',
'latitude'=>37.9601,
'longitude'=>58.3261,
'flag'=>'https://flagcdn.com/w320/tm.png',
],


[
'name'=>'Vatican City',
'code'=>'VA',
'iso2'=>'VA',
'iso3'=>'VAT',
'currency'=>'EUR',
'region'=>'Europe',
'language'=>'Italian',
'capital'=>'Vatican City',
'latitude'=>41.9029,
'longitude'=>12.4534,
'flag'=>'https://flagcdn.com/w320/va.png',
],


[
'name'=>'Liechtenstein',
'code'=>'LI',
'iso2'=>'LI',
'iso3'=>'LIE',
'currency'=>'CHF',
'region'=>'Europe',
'language'=>'German',
'capital'=>'Vaduz',
'latitude'=>47.1416,
'longitude'=>9.5215,
'flag'=>'https://flagcdn.com/w320/li.png',
],


[
'name'=>'Monaco',
'code'=>'MC',
'iso2'=>'MC',
'iso3'=>'MCO',
'currency'=>'EUR',
'region'=>'Europe',
'language'=>'French',
'capital'=>'Monaco',
'latitude'=>43.7384,
'longitude'=>7.4246,
'flag'=>'https://flagcdn.com/w320/mc.png',
],

[
'name'=>'Bahamas',
'code'=>'BS',
'iso2'=>'BS',
'iso3'=>'BHS',
'currency'=>'BSD',
'region'=>'North America',
'language'=>'English',
'capital'=>'Nassau',
'latitude'=>25.0443,
'longitude'=>-77.3504,
'flag'=>'https://flagcdn.com/w320/bs.png',
],


[
'name'=>'Barbados',
'code'=>'BB',
'iso2'=>'BB',
'iso3'=>'BRB',
'currency'=>'BBD',
'region'=>'North America',
'language'=>'English',
'capital'=>'Bridgetown',
'latitude'=>13.0975,
'longitude'=>-59.6167,
'flag'=>'https://flagcdn.com/w320/bb.png',
],


[
'name'=>'Dominica',
'code'=>'DM',
'iso2'=>'DM',
'iso3'=>'DMA',
'currency'=>'XCD',
'region'=>'North America',
'language'=>'English',
'capital'=>'Roseau',
'latitude'=>15.3092,
'longitude'=>-61.3794,
'flag'=>'https://flagcdn.com/w320/dm.png',
],


[
'name'=>'Grenada',
'code'=>'GD',
'iso2'=>'GD',
'iso3'=>'GRD',
'currency'=>'XCD',
'region'=>'North America',
'language'=>'English',
'capital'=>'St George',
'latitude'=>12.0561,
'longitude'=>-61.7488,
'flag'=>'https://flagcdn.com/w320/gd.png',
],


[
'name'=>'Saint Lucia',
'code'=>'LC',
'iso2'=>'LC',
'iso3'=>'LCA',
'currency'=>'XCD',
'region'=>'North America',
'language'=>'English',
'capital'=>'Castries',
'latitude'=>14.0101,
'longitude'=>-60.9875,
'flag'=>'https://flagcdn.com/w320/lc.png',
],


[
'name'=>'Saint Vincent and the Grenadines',
'code'=>'VC',
'iso2'=>'VC',
'iso3'=>'VCT',
'currency'=>'XCD',
'region'=>'North America',
'language'=>'English',
'capital'=>'Kingstown',
'latitude'=>13.1600,
'longitude'=>-61.2248,
'flag'=>'https://flagcdn.com/w320/vc.png',
],


[
'name'=>'Antigua and Barbuda',
'code'=>'AG',
'iso2'=>'AG',
'iso3'=>'ATG',
'currency'=>'XCD',
'region'=>'North America',
'language'=>'English',
'capital'=>'Saint Johns',
'latitude'=>17.1274,
'longitude'=>-61.8468,
'flag'=>'https://flagcdn.com/w320/ag.png',
],


[
'name'=>'Haiti',
'code'=>'HT',
'iso2'=>'HT',
'iso3'=>'HTI',
'currency'=>'HTG',
'region'=>'North America',
'language'=>'French',
'capital'=>'Port-au-Prince',
'latitude'=>18.5944,
'longitude'=>-72.3074,
'flag'=>'https://flagcdn.com/w320/ht.png',
],


[
'name'=>'Suriname',
'code'=>'SR',
'iso2'=>'SR',
'iso3'=>'SUR',
'currency'=>'SRD',
'region'=>'South America',
'language'=>'Dutch',
'capital'=>'Paramaribo',
'latitude'=>5.8520,
'longitude'=>-55.2038,
'flag'=>'https://flagcdn.com/w320/sr.png',
],


[
'name'=>'French Guiana',
'code'=>'GF',
'iso2'=>'GF',
'iso3'=>'GUF',
'currency'=>'EUR',
'region'=>'South America',
'language'=>'French',
'capital'=>'Cayenne',
'latitude'=>4.9224,
'longitude'=>-52.3135,
'flag'=>'https://flagcdn.com/w320/gf.png',
],


[
'name'=>'Belize',
'code'=>'BZ',
'iso2'=>'BZ',
'iso3'=>'BLZ',
'currency'=>'BZD',
'region'=>'North America',
'language'=>'English',
'capital'=>'Belmopan',
'latitude'=>17.2510,
'longitude'=>-88.7590,
'flag'=>'https://flagcdn.com/w320/bz.png',
],


[
'name'=>'Cape Verde',
'code'=>'CV',
'iso2'=>'CV',
'iso3'=>'CPV',
'currency'=>'CVE',
'region'=>'Africa',
'language'=>'Portuguese',
'capital'=>'Praia',
'latitude'=>14.9330,
'longitude'=>-23.5133,
'flag'=>'https://flagcdn.com/w320/cv.png',
],


[
'name'=>'Gabon',
'code'=>'GA',
'iso2'=>'GA',
'iso3'=>'GAB',
'currency'=>'XAF',
'region'=>'Africa',
'language'=>'French',
'capital'=>'Libreville',
'latitude'=>0.4162,
'longitude'=>9.4673,
'flag'=>'https://flagcdn.com/w320/ga.png',
],


[
'name'=>'Guinea',
'code'=>'GN',
'iso2'=>'GN',
'iso3'=>'GIN',
'currency'=>'GNF',
'region'=>'Africa',
'language'=>'French',
'capital'=>'Conakry',
'latitude'=>9.6412,
'longitude'=>-13.5784,
'flag'=>'https://flagcdn.com/w320/gn.png',
],


[
'name'=>'Guinea-Bissau',
'code'=>'GW',
'iso2'=>'GW',
'iso3'=>'GNB',
'currency'=>'XOF',
'region'=>'Africa',
'language'=>'Portuguese',
'capital'=>'Bissau',
'latitude'=>11.8636,
'longitude'=>-15.5977,
'flag'=>'https://flagcdn.com/w320/gw.png',
],


[
'name'=>'Liberia',
'code'=>'LR',
'iso2'=>'LR',
'iso3'=>'LBR',
'currency'=>'LRD',
'region'=>'Africa',
'language'=>'English',
'capital'=>'Monrovia',
'latitude'=>6.3156,
'longitude'=>-10.8074,
'flag'=>'https://flagcdn.com/w320/lr.png',
],


[
'name'=>'Mali',
'code'=>'ML',
'iso2'=>'ML',
'iso3'=>'MLI',
'currency'=>'XOF',
'region'=>'Africa',
'language'=>'French',
'capital'=>'Bamako',
'latitude'=>12.6392,
'longitude'=>-8.0029,
'flag'=>'https://flagcdn.com/w320/ml.png',
],


[
'name'=>'Niger',
'code'=>'NE',
'iso2'=>'NE',
'iso3'=>'NER',
'currency'=>'XOF',
'region'=>'Africa',
'language'=>'French',
'capital'=>'Niamey',
'latitude'=>13.5116,
'longitude'=>2.1254,
'flag'=>'https://flagcdn.com/w320/ne.png',
],


[
'name'=>'Chad',
'code'=>'TD',
'iso2'=>'TD',
'iso3'=>'TCD',
'currency'=>'XAF',
'region'=>'Africa',
'language'=>'French',
'capital'=>'N Djamena',
'latitude'=>12.1348,
'longitude'=>15.0557,
'flag'=>'https://flagcdn.com/w320/td.png',
],


[
'name'=>'Burkina Faso',
'code'=>'BF',
'iso2'=>'BF',
'iso3'=>'BFA',
'currency'=>'XOF',
'region'=>'Africa',
'language'=>'French',
'capital'=>'Ouagadougou',
'latitude'=>12.3714,
'longitude'=>-1.5197,
'flag'=>'https://flagcdn.com/w320/bf.png',
],


[
'name'=>'Togo',
'code'=>'TG',
'iso2'=>'TG',
'iso3'=>'TGO',
'currency'=>'XOF',
'region'=>'Africa',
'language'=>'French',
'capital'=>'Lome',
'latitude'=>6.1256,
'longitude'=>1.2254,
'flag'=>'https://flagcdn.com/w320/tg.png',
],


[
'name'=>'Benin',
'code'=>'BJ',
'iso2'=>'BJ',
'iso3'=>'BEN',
'currency'=>'XOF',
'region'=>'Africa',
'language'=>'French',
'capital'=>'Porto Novo',
'latitude'=>6.4969,
'longitude'=>2.6289,
'flag'=>'https://flagcdn.com/w320/bj.png',
],


[
'name'=>'Central African Republic',
'code'=>'CF',
'iso2'=>'CF',
'iso3'=>'CAF',
'currency'=>'XAF',
'region'=>'Africa',
'language'=>'French',
'capital'=>'Bangui',
'latitude'=>4.3947,
'longitude'=>18.5582,
'flag'=>'https://flagcdn.com/w320/cf.png',
],


[
'name'=>'Republic of Congo',
'code'=>'CG',
'iso2'=>'CG',
'iso3'=>'COG',
'currency'=>'XAF',
'region'=>'Africa',
'language'=>'French',
'capital'=>'Brazzaville',
'latitude'=>-4.2634,
'longitude'=>15.2429,
'flag'=>'https://flagcdn.com/w320/cg.png',
],

[
'name'=>'Lesotho',
'code'=>'LS',
'iso2'=>'LS',
'iso3'=>'LSO',
'currency'=>'LSL',
'region'=>'Africa',
'language'=>'English',
'capital'=>'Maseru',
'latitude'=>-29.3151,
'longitude'=>27.4869,
'flag'=>'https://flagcdn.com/w320/ls.png',
],


[
'name'=>'Eswatini',
'code'=>'SZ',
'iso2'=>'SZ',
'iso3'=>'SWZ',
'currency'=>'SZL',
'region'=>'Africa',
'language'=>'English',
'capital'=>'Mbabane',
'latitude'=>-26.3054,
'longitude'=>31.1367,
'flag'=>'https://flagcdn.com/w320/sz.png',
],


[
'name'=>'Mauritania',
'code'=>'MR',
'iso2'=>'MR',
'iso3'=>'MRT',
'currency'=>'MRU',
'region'=>'Africa',
'language'=>'Arabic',
'capital'=>'Nouakchott',
'latitude'=>18.0735,
'longitude'=>-15.9582,
'flag'=>'https://flagcdn.com/w320/mr.png',
],


[
'name'=>'Sierra Leone',
'code'=>'SL',
'iso2'=>'SL',
'iso3'=>'SLE',
'currency'=>'SLL',
'region'=>'Africa',
'language'=>'English',
'capital'=>'Freetown',
'latitude'=>8.4657,
'longitude'=>-13.2317,
'flag'=>'https://flagcdn.com/w320/sl.png',
],


[
'name'=>'South Sudan',
'code'=>'SS',
'iso2'=>'SS',
'iso3'=>'SSD',
'currency'=>'SSP',
'region'=>'Africa',
'language'=>'English',
'capital'=>'Juba',
'latitude'=>4.8594,
'longitude'=>31.5713,
'flag'=>'https://flagcdn.com/w320/ss.png',
],


[
'name'=>'Eritrea',
'code'=>'ER',
'iso2'=>'ER',
'iso3'=>'ERI',
'currency'=>'ERN',
'region'=>'Africa',
'language'=>'Tigrinya',
'capital'=>'Asmara',
'latitude'=>15.3229,
'longitude'=>38.9251,
'flag'=>'https://flagcdn.com/w320/er.png',
],


[
'name'=>'Djibouti',
'code'=>'DJ',
'iso2'=>'DJ',
'iso3'=>'DJI',
'currency'=>'DJF',
'region'=>'Africa',
'language'=>'French',
'capital'=>'Djibouti',
'latitude'=>11.5721,
'longitude'=>43.1456,
'flag'=>'https://flagcdn.com/w320/dj.png',
],


[
'name'=>'Comoros',
'code'=>'KM',
'iso2'=>'KM',
'iso3'=>'COM',
'currency'=>'KMF',
'region'=>'Africa',
'language'=>'French',
'capital'=>'Moroni',
'latitude'=>-11.7172,
'longitude'=>43.2473,
'flag'=>'https://flagcdn.com/w320/km.png',
],


[
'name'=>'Equatorial Guinea',
'code'=>'GQ',
'iso2'=>'GQ',
'iso3'=>'GNQ',
'currency'=>'XAF',
'region'=>'Africa',
'language'=>'Spanish',
'capital'=>'Malabo',
'latitude'=>3.7504,
'longitude'=>8.7371,
'flag'=>'https://flagcdn.com/w320/gq.png',
],


[
'name'=>'Sao Tome and Principe',
'code'=>'ST',
'iso2'=>'ST',
'iso3'=>'STP',
'currency'=>'STN',
'region'=>'Africa',
'language'=>'Portuguese',
'capital'=>'Sao Tome',
'latitude'=>0.3365,
'longitude'=>6.7273,
'flag'=>'https://flagcdn.com/w320/st.png',
],


[
'name'=>'Afghanistan',
'code'=>'AF',
'iso2'=>'AF',
'iso3'=>'AFG',
'currency'=>'AFN',
'region'=>'Asia',
'language'=>'Pashto',
'capital'=>'Kabul',
'latitude'=>34.5553,
'longitude'=>69.2075,
'flag'=>'https://flagcdn.com/w320/af.png',
],


[
'name'=>'Maldives',
'code'=>'MV',
'iso2'=>'MV',
'iso3'=>'MDV',
'currency'=>'MVR',
'region'=>'Asia',
'language'=>'Dhivehi',
'capital'=>'Male',
'latitude'=>4.1755,
'longitude'=>73.5093,
'flag'=>'https://flagcdn.com/w320/mv.png',
],


[
'name'=>'North Korea',
'code'=>'KP',
'iso2'=>'KP',
'iso3'=>'PRK',
'currency'=>'KPW',
'region'=>'Asia',
'language'=>'Korean',
'capital'=>'Pyongyang',
'latitude'=>39.0392,
'longitude'=>125.7625,
'flag'=>'https://flagcdn.com/w320/kp.png',
],


[
'name'=>'Bhutan',
'code'=>'BT',
'iso2'=>'BT',
'iso3'=>'BTN',
'currency'=>'BTN',
'region'=>'Asia',
'language'=>'Dzongkha',
'capital'=>'Thimphu',
'latitude'=>27.4728,
'longitude'=>89.6390,
'flag'=>'https://flagcdn.com/w320/bt.png',
],


[
'name'=>'Andorra',
'code'=>'AD',
'iso2'=>'AD',
'iso3'=>'AND',
'currency'=>'EUR',
'region'=>'Europe',
'language'=>'Catalan',
'capital'=>'Andorra la Vella',
'latitude'=>42.5063,
'longitude'=>1.5218,
'flag'=>'https://flagcdn.com/w320/ad.png',
],


[
'name'=>'San Marino',
'code'=>'SM',
'iso2'=>'SM',
'iso3'=>'SMR',
'currency'=>'EUR',
'region'=>'Europe',
'language'=>'Italian',
'capital'=>'San Marino',
'latitude'=>43.9424,
'longitude'=>12.4578,
'flag'=>'https://flagcdn.com/w320/sm.png',
],


[
'name'=>'Liechtenstein',
'code'=>'LI',
'iso2'=>'LI',
'iso3'=>'LIE',
'currency'=>'CHF',
'region'=>'Europe',
'language'=>'German',
'capital'=>'Vaduz',
'latitude'=>47.1416,
'longitude'=>9.5215,
'flag'=>'https://flagcdn.com/w320/li.png',
],


[
'name'=>'Monaco',
'code'=>'MC',
'iso2'=>'MC',
'iso3'=>'MCO',
'currency'=>'EUR',
'region'=>'Europe',
'language'=>'French',
'capital'=>'Monaco',
'latitude'=>43.7384,
'longitude'=>7.4246,
'flag'=>'https://flagcdn.com/w320/mc.png',
],


[
'name'=>'Palestine',
'code'=>'PS',
'iso2'=>'PS',
'iso3'=>'PSE',
'currency'=>'ILS',
'region'=>'Asia',
'language'=>'Arabic',
'capital'=>'Ramallah',
'latitude'=>31.9038,
'longitude'=>35.2034,
'flag'=>'https://flagcdn.com/w320/ps.png',
],


[
'name'=>'Kosovo',
'code'=>'XK',
'iso2'=>'XK',
'iso3'=>'XKX',
'currency'=>'EUR',
'region'=>'Europe',
'language'=>'Albanian',
'capital'=>'Pristina',
'latitude'=>42.6629,
'longitude'=>21.1655,
'flag'=>'https://flagcdn.com/w320/xk.png',
],


[
'name'=>'Fiji',
'code'=>'FJ',
'iso2'=>'FJ',
'iso3'=>'FJI',
'currency'=>'FJD',
'region'=>'Oceania',
'language'=>'English',
'capital'=>'Suva',
'latitude'=>-18.1416,
'longitude'=>178.4419,
'flag'=>'https://flagcdn.com/w320/fj.png',
],


[
'name'=>'Kiribati',
'code'=>'KI',
'iso2'=>'KI',
'iso3'=>'KIR',
'currency'=>'AUD',
'region'=>'Oceania',
'language'=>'English',
'capital'=>'Tarawa',
'latitude'=>1.4518,
'longitude'=>173.0320,
'flag'=>'https://flagcdn.com/w320/ki.png',
],


[
'name'=>'Micronesia',
'code'=>'FM',
'iso2'=>'FM',
'iso3'=>'FSM',
'currency'=>'USD',
'region'=>'Oceania',
'language'=>'English',
'capital'=>'Palikir',
'latitude'=>6.9248,
'longitude'=>158.1610,
'flag'=>'https://flagcdn.com/w320/fm.png',
],


[
'name'=>'Nauru',
'code'=>'NR',
'iso2'=>'NR',
'iso3'=>'NRU',
'currency'=>'AUD',
'region'=>'Oceania',
'language'=>'English',
'capital'=>'Yaren',
'latitude'=>-0.5477,
'longitude'=>166.9209,
'flag'=>'https://flagcdn.com/w320/nr.png',
],


[
'name'=>'Tuvalu',
'code'=>'TV',
'iso2'=>'TV',
'iso3'=>'TUV',
'currency'=>'AUD',
'region'=>'Oceania',
'language'=>'English',
'capital'=>'Funafuti',
'latitude'=>-8.5211,
'longitude'=>179.1982,
'flag'=>'https://flagcdn.com/w320/tv.png',
],

[
'name'=>'Antarctica',
'code'=>'AQ',
'iso2'=>'AQ',
'iso3'=>'ATA',
'currency'=>'USD',
'region'=>'Antarctica',
'language'=>'English',
'capital'=>'Research Stations',
'latitude'=>-82.8628,
'longitude'=>135.0000,
'flag'=>'https://flagcdn.com/w320/aq.png',
],


[
'name'=>'American Samoa',
'code'=>'AS',
'iso2'=>'AS',
'iso3'=>'ASM',
'currency'=>'USD',
'region'=>'Oceania',
'language'=>'English',
'capital'=>'Pago Pago',
'latitude'=>-14.2756,
'longitude'=>-170.7020,
'flag'=>'https://flagcdn.com/w320/as.png',
],


[
'name'=>'Cook Islands',
'code'=>'CK',
'iso2'=>'CK',
'iso3'=>'COK',
'currency'=>'NZD',
'region'=>'Oceania',
'language'=>'English',
'capital'=>'Avarua',
'latitude'=>-21.2070,
'longitude'=>-159.7750,
'flag'=>'https://flagcdn.com/w320/ck.png',
],


[
'name'=>'Niue',
'code'=>'NU',
'iso2'=>'NU',
'iso3'=>'NIU',
'currency'=>'NZD',
'region'=>'Oceania',
'language'=>'English',
'capital'=>'Alofi',
'latitude'=>-19.0554,
'longitude'=>-169.9179,
'flag'=>'https://flagcdn.com/w320/nu.png',
],


[
'name'=>'New Caledonia',
'code'=>'NC',
'iso2'=>'NC',
'iso3'=>'NCL',
'currency'=>'XPF',
'region'=>'Oceania',
'language'=>'French',
'capital'=>'Noumea',
'latitude'=>-22.2758,
'longitude'=>166.4580,
'flag'=>'https://flagcdn.com/w320/nc.png',
],


[
'name'=>'French Polynesia',
'code'=>'PF',
'iso2'=>'PF',
'iso3'=>'PYF',
'currency'=>'XPF',
'region'=>'Oceania',
'language'=>'French',
'capital'=>'Papeete',
'latitude'=>-17.5516,
'longitude'=>-149.5585,
'flag'=>'https://flagcdn.com/w320/pf.png',
],


[
'name'=>'Guam',
'code'=>'GU',
'iso2'=>'GU',
'iso3'=>'GUM',
'currency'=>'USD',
'region'=>'Oceania',
'language'=>'English',
'capital'=>'Hagatna',
'latitude'=>13.4443,
'longitude'=>144.7937,
'flag'=>'https://flagcdn.com/w320/gu.png',
],


[
'name'=>'Northern Mariana Islands',
'code'=>'MP',
'iso2'=>'MP',
'iso3'=>'MNP',
'currency'=>'USD',
'region'=>'Oceania',
'language'=>'English',
'capital'=>'Saipan',
'latitude'=>15.1778,
'longitude'=>145.7500,
'flag'=>'https://flagcdn.com/w320/mp.png',
],


[
'name'=>'Aruba',
'code'=>'AW',
'iso2'=>'AW',
'iso3'=>'ABW',
'currency'=>'AWG',
'region'=>'North America',
'language'=>'Dutch',
'capital'=>'Oranjestad',
'latitude'=>12.5211,
'longitude'=>-70.0371,
'flag'=>'https://flagcdn.com/w320/aw.png',
],


[
'name'=>'Curacao',
'code'=>'CW',
'iso2'=>'CW',
'iso3'=>'CUW',
'currency'=>'ANG',
'region'=>'North America',
'language'=>'Dutch',
'capital'=>'Willemstad',
'latitude'=>12.1696,
'longitude'=>-68.9900,
'flag'=>'https://flagcdn.com/w320/cw.png',
],


[
'name'=>'Bermuda',
'code'=>'BM',
'iso2'=>'BM',
'iso3'=>'BMU',
'currency'=>'BMD',
'region'=>'North America',
'language'=>'English',
'capital'=>'Hamilton',
'latitude'=>32.2948,
'longitude'=>-64.7814,
'flag'=>'https://flagcdn.com/w320/bm.png',
],


[
'name'=>'Cayman Islands',
'code'=>'KY',
'iso2'=>'KY',
'iso3'=>'CYM',
'currency'=>'KYD',
'region'=>'North America',
'language'=>'English',
'capital'=>'George Town',
'latitude'=>19.3133,
'longitude'=>-81.2546,
'flag'=>'https://flagcdn.com/w320/ky.png',
],


[
'name'=>'Puerto Rico',
'code'=>'PR',
'iso2'=>'PR',
'iso3'=>'PRI',
'currency'=>'USD',
'region'=>'North America',
'language'=>'Spanish',
'capital'=>'San Juan',
'latitude'=>18.4655,
'longitude'=>-66.1057,
'flag'=>'https://flagcdn.com/w320/pr.png',
],


[
'name'=>'Greenland',
'code'=>'GL',
'iso2'=>'GL',
'iso3'=>'GRL',
'currency'=>'DKK',
'region'=>'North America',
'language'=>'Greenlandic',
'capital'=>'Nuuk',
'latitude'=>64.1835,
'longitude'=>-51.7216,
'flag'=>'https://flagcdn.com/w320/gl.png',
],


[
'name'=>'Faroe Islands',
'code'=>'FO',
'iso2'=>'FO',
'iso3'=>'FRO',
'currency'=>'DKK',
'region'=>'Europe',
'language'=>'Faroese',
'capital'=>'Torshavn',
'latitude'=>62.0079,
'longitude'=>-6.7900,
'flag'=>'https://flagcdn.com/w320/fo.png',
],


[
'name'=>'Gibraltar',
'code'=>'GI',
'iso2'=>'GI',
'iso3'=>'GIB',
'currency'=>'GIP',
'region'=>'Europe',
'language'=>'English',
'capital'=>'Gibraltar',
'latitude'=>36.1408,
'longitude'=>-5.3536,
'flag'=>'https://flagcdn.com/w320/gi.png',
],


[
'name'=>'Jersey',
'code'=>'JE',
'iso2'=>'JE',
'iso3'=>'JEY',
'currency'=>'GBP',
'region'=>'Europe',
'language'=>'English',
'capital'=>'Saint Helier',
'latitude'=>49.1868,
'longitude'=>-2.1060,
'flag'=>'https://flagcdn.com/w320/je.png',
],


[
'name'=>'Guernsey',
'code'=>'GG',
'iso2'=>'GG',
'iso3'=>'GGY',
'currency'=>'GBP',
'region'=>'Europe',
'language'=>'English',
'capital'=>'Saint Peter Port',
'latitude'=>49.4555,
'longitude'=>-2.5369,
'flag'=>'https://flagcdn.com/w320/gg.png',
],


[
'name'=>'Isle of Man',
'code'=>'IM',
'iso2'=>'IM',
'iso3'=>'IMN',
'currency'=>'GBP',
'region'=>'Europe',
'language'=>'English',
'capital'=>'Douglas',
'latitude'=>54.1523,
'longitude'=>-4.4861,
'flag'=>'https://flagcdn.com/w320/im.png',
],


[
'name'=>'Western Sahara',
'code'=>'EH',
'iso2'=>'EH',
'iso3'=>'ESH',
'currency'=>'MAD',
'region'=>'Africa',
'language'=>'Arabic',
'capital'=>'Laayoune',
'latitude'=>27.1253,
'longitude'=>-13.1625,
'flag'=>'https://flagcdn.com/w320/eh.png',
],

        ];

        foreach($countries as $country){

            Country::updateOrCreate(

                ['code'=>$country['code']],

                $country

            );

        }

        $this->command->info('50 Countries Imported Successfully');

    }
}